service: colosseum-github-webhook

custom:
  stage: ${opt:stage, 'dev'}
  serverless-offline:
    host: 0.0.0.0
    httpPort: 4000

provider:
  name: aws
  region: ${opt:region, 'ap-northeast-2'}
  runtime: nodejs18.x
  architecture: arm64
  stage: ${self:custom.stage}
  memorySize: 128
  timeout: 10

functions:
  webhook:
    handler: build/main.webhook
    events:
      - http:
          path: /github/webhook
          method: post
          cors: true

resources:
  Resources:
    LambdaRole: ${file(./res/lambda-role.yml)}

plugins:
  - serverless-offline
